### ISSUE TITLE
Feature Request: Allow launching the in-app WebView without the extra flow

### ISSUE THREAD

**Issue by briankariuki** [Flutterwave/Flutter#18]
Feature request!

Would it be possible to allow just calling the function that launches the in-app web view without having to go through the extra flow you've added into the package. Doing this would allow us to add our own custom flows before launching the in-app webview.

Thanks.

![Screenshot 2022-07-14 at 09 14 25](https://user-images.githubusercontent.com/34672053/178913119-51ab9878-a785-4b07-92f7-b28873c956be.png)

**Comment by Devlonoah** [comment]
you are right @briankariuki , i second that

**Comment by FredDominant** [comment]
@briankariuki, @Devlonoah, Thank you for your kind feedback. This is already in development.
