### ISSUE TITLE
Customer not defined, and The class 'Flutterwave' doesn't have an unnamed constructor 

### ISSUE THREAD

**Issue by Mundia-Pizo** [Flutterwave/Flutter#25]
Can't use the new flutterwave pluggin am getting the  error when calling the the 
 final Flutterwave flutterwave = Flutterwave(
        context: context,
        style: style,
        publicKey: "Public Key",
        currency: "RWF",
        redirectUrl: "my_redirect_url",
        txRef: "unique_transaction_reference",
        amount: "3000",
        customer: customer,
        paymentOptions: "ussd, card, barter, payattitude",
        customization: Customization(title: "Test Payment"),
        isDebug: true);
it says flutter wave doesn't have unamend constructor i dont know which package to import for this error to go

**Comment by FredDominant** [comment]
Hello @Mundia-Pizo, could you state on what version of the library do you encounter this?

**Comment by Mundia-Pizo** [comment]
I think ai was using the older version of the flutterwave checkout i kind
of figuured out the solution
