### ISSUE TITLE
ChargeResponse has no null safety

### ISSUE THREAD

**Issue by Mundia-Pizo** [Flutterwave/Flutter#27]
If a transaction is cancelled from the card form or any payment method form an exception is thrown with the charge response has no null safety, this happens also if the transaction is closed from the payment page.

**Comment by huzaifansari54** [comment]
i solve it check #29

**Comment by Mundia-Pizo** [comment]
The problem still persists did you try it  out ?

**Comment by definitelyme** [comment]
Check out the open PR #5. You can use the temporary fix until this issue is resolved.

**Comment by FredDominant** [comment]
This has been addressed in version 1[.0.5](https://pub.dev/packages/flutterwave_standard/versions/1.0.5)

**Comment by Mundia-Pizo** [comment]
> This has been addressed in version 1[.0.5](https://pub.dev/packages/flutterwave_standard/versions/1.0.5)

This is great now thanks @FredDominant
