### ISSUE TITLE
Charge response cannot handle a null repose when use cancels transaction and also blank page with one button not good for user experience

### ISSUE THREAD

**Issue by Mundia-Pizo** [Flutterwave/Flutter#29]
ChargeResponse cannot handle a null response when user cancels transaction , and also have a page with just one Makepayment button is not good for user experience I would like from checkout the user is redirected to the payment page where they enter their payment details without going through the second page for make payment.
<img width="212" alt="pyment page" src="https://user-images.githubusercontent.com/41225858/194710923-257bc835-49ea-4b34-8a25-5b18eefd322f.png">
 now going strait to this page instead of going through the one on top 
<img width="335" alt="page1" src="https://user-images.githubusercontent.com/41225858/194711003-5c6a9d6e-7f30-4e58-a59a-c085676b9ae4.png">

This is the charge response error for the a cancelled transaction
<img width="659" alt="ChargeResponse error" src="https://user-images.githubusercontent.com/41225858/194711288-d48f69ff-e495-4122-a570-3c34a180b8d3.png">

**Comment by huzaifansari54** [comment]
hello sir can i work on this issue

**Comment by Mundia-Pizo** [comment]
> hello sir can i work on this issue

Yes of course I need it solved

**Comment by huzaifansari54** [comment]
i check it this problem is occur becouse of null safety an di solve it

**Comment by definitelyme** [comment]
Check out the open PR #5. You can use the temporary fix until this issue is resolved.

**Comment by FredDominant** [comment]
@definitelyme, @Mundia-Pizo This has been fixed in the new update.
