### ISSUE TITLE
Error launching application on iOS after installing Flutterwave

### ISSUE THREAD

**Issue by binemmanuel** [Flutterwave/Flutter#33]
`Launching lib/main.dart on iPhone 13 Pro Max in debug mode...
Running Xcode build...                                                  
Xcode build done.                                            4.1s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-10-25 14:15:44.059 xcodebuild[54003:9915111] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    2022-10-25 14:15:44.059 xcodebuild[54003:9915111] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
    Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/_6/xqc5vz311qz_5mm6whbxz_v00000gp/T/flutter_tools.hNkkkn/flutter_ios_build_temp_dirCTvsKh/temporary_xcresult_bundle

    /Users/binemmanuel/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.1/ios/Classes/MyCookieManager.swift:260:44: error: cannot call value of non-function type 'String?'
                            domain = domainUrl.host()
                                               ^   ~~

    /Users/binemmanuel/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.1/ios/Classes/MyCookieManager.swift:294:44: error: cannot call value of non-function type 'String?'
                            domain = domainUrl.host()
                                               ^   ~~

    /Users/binemmanuel/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.1/ios/Classes/InAppBrowser/InAppBrowserWebViewController.swift:565:13: warning: setter for 'statusBarStyle' was deprecated in iOS 9.0: Use -[UIViewController
    preferredStatusBarStyle]
                UIApplication.shared.statusBarStyle = UIStatusBarStyle(rawValue: previousStatusBarStyle)!
                ^
    /Users/binemmanuel/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.1/ios/Classes/MyCookieManager.swift:260:44: error: cannot call value of non-function type 'String?'
                            domain = domainUrl.host()
                                               ^   ~~

    /Users/binemmanuel/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.1/ios/Classes/MyCookieManager.swift:294:44: error: cannot call value of non-function type 'String?'
                            domain = domainUrl.host()
                                               ^   ~~

    /Users/binemmanuel/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.1/ios/Classes/InAppBrowser/InAppBrowserWebViewController.swift:565:13: warning: setter for 'statusBarStyle' was deprecated in iOS 9.0: Use -[UIViewController
    preferredStatusBarStyle]
                UIApplication.shared.statusBarStyle = UIStatusBarStyle(rawValue: previousStatusBarStyle)!
                ^
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/binemmanuel/Projects/gasport/frontend/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in
    target 'Toast' from project 'Pods')
    /Users/binemmanuel/Projects/gasport/frontend/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in
    target 'OrderedSet' from project 'Pods')
    /Users/binemmanuel/Projects/gasport/frontend/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in
    target 'FMDB' from project 'Pods')

    Result bundle written to path:
        /var/folders/_6/xqc5vz311qz_5mm6whbxz_v00000gp/T/flutter_tools.hNkkkn/flutter_ios_build_temp_dirCTvsKh/temporary_xcresult_bundle

Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/binemmanuel/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.1/ios/Classes/MyCookieManager.swift:259:43

Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/binemmanuel/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.1/ios/Classes/MyCookieManager.swift:293:43

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro Max.`

**Comment by FredDominant** [comment]
Hello @binemmanuel, please checkout the new version [here](https://pub.dev/packages/flutterwave_standard/versions/1.0.6)

**Comment by binemmanuel** [comment]
The newer versions fix the problem
