### ISSUE TITLE
Cors block

### ISSUE THREAD

**Issue by stanonyime** [Flutterwave/Flutter#4]
I am getting a CORS issue with this. 
```Access to XMLHttpRequest at 'https://ravesandboxapi.flutterwave.com/v3/sdkcheckout/payments' from origin 'http://localhost:54475' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status```

**Comment by FredDominant** [comment]
Hello @stanonyime, please note that this is a mobile-only library. Please make use of our web libraries to use Flutterwave on the web.
